import mongoose from 'mongoose';
import crypto from 'crypto';

import Chama from '../models/Chama.js';
import ChamaMembership from '../models/ChamaMembership.js';
import ChamaMemberKyc from '../models/ChamaMemberKyc.js';
import ChamaLoan from '../models/ChamaLoan.js';
import Dispute from '../models/Dispute.js';
import OfficialRating from '../models/Officialrating.js';
import ApprovalRequest from '../models/ApprovalRequest.js';
import ChamaTrustScore from '../models/ChamaTrustScore.js';

import AppError from '../utils/AppError.js';

import { createAuditLog, verifyAuditChain, AUDIT_SCOPE_TYPES } from './audit.service.js';

import {
  OFFICIAL_ROLES,
  TRUST_SCORE_WEIGHTS,
  gradeForScore,
  DISPUTE_LOOKBACK_DAYS,
  DISPUTE_STATUS_WEIGHT,
  HIGH_VALUE_COSIGN_RESOURCE_TYPES,
  MIN_REQUIRED_COSIGNERS,
  OFFICIAL_RATING_MIN,
  OFFICIAL_RATING_MAX,
} from '../constants/Trustscore.constants.js';

import { AUDIT_ACTIONS } from '../constants/audit.constants.js';

// ========================================
// CHAMA TRUST SCORE SERVICE
// ========================================
//
// Computes the shareable Chama Trust Score: a single number (plus an
// inspectable breakdown) that summarizes, from data the chama has
// already generated by operating normally, how much a bank, SACCO
// federation, or prospective member should trust this group.
//
// Every component below reads from records that already exist for
// other reasons (loan schedules, KYC records, the audit hash chain,
// approval requests) plus two records this feature adds for exactly
// this purpose (Dispute, OfficialRating). Nothing here mutates any of
// those source records — this is a read-and-summarize service, and the
// only thing it writes is its own snapshot + an audit log entry noting
// that a score was generated/shared.
//
// ========================================

const validateObjectId = (value, fieldName) => {
  if (!value || !mongoose.Types.ObjectId.isValid(value)) {
    throw new AppError(`Invalid ${fieldName}`, 400);
  }
};

// ========================================
// WEIGHT RENORMALIZATION
// ========================================
//
// Given the full weight map and which component keys actually have
// data, returns weights for just the data-bearing keys, rescaled to
// still sum to 1. A chama with zero loans ever issued isn't penalized
// with a 0 for "repayment reliability" — that component is dropped and
// the other four pick up its weight proportionally.
//
// ========================================

const normalizeWeights = (componentsWithData) => {
  const totalWeight = componentsWithData.reduce(
    (sum, key) => sum + (TRUST_SCORE_WEIGHTS[key] || 0),
    0
  );

  if (totalWeight <= 0) return {};

  return componentsWithData.reduce((acc, key) => {
    acc[key] = (TRUST_SCORE_WEIGHTS[key] || 0) / totalWeight;
    return acc;
  }, {});
};

// ========================================
// COMPONENT 1 — REPAYMENT RELIABILITY
// ========================================
//
// Across every loan this chama has ever issued, of the installments
// that have come due, what fraction were paid in full on or before
// their due date? Installments not yet due are excluded entirely —
// this measures track record, not how many loans happen to be mid-term
// right now.
//
// ========================================

const computeRepaymentReliability = async (chamaId) => {
  const loans = await ChamaLoan.find({ chama_id: chamaId })
    .select('repayment_schedule')
    .lean();

  const now = new Date();
  let totalDue = 0;
  let onTime = 0;

  for (const loan of loans) {
    for (const item of loan.repayment_schedule || []) {
      if (!item.due_date || new Date(item.due_date) > now) continue; // not yet due

      totalDue += 1;

      const paidInFull = item.status === 'paid';
      const paidOnTime =
        paidInFull && item.paid_at && new Date(item.paid_at) <= new Date(item.due_date);

      if (paidOnTime) onTime += 1;
    }
  }

  const hasData = totalDue > 0;
  const rate = hasData ? onTime / totalDue : null;

  return {
    hasData,
    score: hasData ? Math.round(rate * 100) : null,
    rate,
    onTimeCount: onTime,
    totalDueCount: totalDue,
  };
};

// ========================================
// COMPONENT 2 — ACTIVE KYC COVERAGE
// ========================================

const computeKycCoverage = async (chamaId) => {
  const activeMemberships = await ChamaMembership.find({
    chama_id: chamaId,
    status: 'active',
  })
    .select('_id')
    .lean();

  const activeMemberCount = activeMemberships.length;
  const hasData = activeMemberCount > 0;

  const verifiedCount = hasData
    ? await ChamaMemberKyc.countDocuments({
        chama_id: chamaId,
        status: 'verified',
        membership_id: { $in: activeMemberships.map((m) => m._id) },
      })
    : 0;

  const rate = hasData ? verifiedCount / activeMemberCount : null;

  return {
    hasData,
    score: hasData ? Math.round(rate * 100) : null,
    rate,
    verifiedCount,
    activeMemberCount,
  };
};

// ========================================
// COMPONENT 3 — DISPUTE RATE
// ========================================
//
// Severity-weighted disputes raised in the trailing DISPUTE_LOOKBACK_
// DAYS, relative to active membership size. An open, unresolved
// dispute costs the most; a dismissed one (found to be without merit)
// costs nothing — see DISPUTE_STATUS_WEIGHT.
//
// ========================================

const computeDisputeRate = async (chamaId, activeMemberCount) => {
  const hasData = activeMemberCount > 0;
  if (!hasData) {
    return { hasData: false, score: null, rate: null, openCount: 0, totalCount: 0 };
  }

  const since = new Date(Date.now() - DISPUTE_LOOKBACK_DAYS * 24 * 60 * 60 * 1000);

  const disputes = await Dispute.find({ chama_id: chamaId, createdAt: { $gte: since } })
    .select('status')
    .lean();

  const weightedCount = disputes.reduce(
    (sum, d) => sum + (DISPUTE_STATUS_WEIGHT[d.status] ?? 1),
    0
  );

  const openCount = disputes.filter((d) => ['open', 'investigating'].includes(d.status)).length;

  const rate = Math.min(weightedCount / activeMemberCount, 1);

  return {
    hasData: true,
    score: Math.round((1 - rate) * 100),
    rate,
    openCount,
    totalCount: disputes.length,
  };
};

// ========================================
// COMPONENT 4 — AUDIT COMPLETENESS / INTEGRITY
// ========================================
//
// Re-walks this chama's hash-chain audit trail (the same check exposed
// to members via "Verify this record" on the Trust Timeline) and scores
// it: a fully intact chain scores 100; any detected break scores low,
// proportional to how much of the chain still verifies before the
// break. This is "audit completeness" in the sense that matters to an
// outside party — not just that logs exist, but that the log hasn't
// been tampered with since it was written.
//
// ========================================

const computeAuditIntegrity = async (chamaId) => {
  const result = await verifyAuditChain({ scopeType: AUDIT_SCOPE_TYPES.CHAMA, chamaId });

  const hasData = result.totalEntries > 0;
  if (!hasData) {
    return { hasData: false, score: null, valid: null, verifiedEntries: 0, totalEntries: 0 };
  }

  const score = result.valid
    ? 100
    : Math.round((result.verifiedEntries / Math.max(result.totalEntries, 1)) * 60);
  // A broken chain is capped at 60 even if most entries still verify —
  // integrity failures are treated as severe, not proportionally minor.

  return {
    hasData: true,
    score,
    valid: result.valid,
    verifiedEntries: result.verifiedEntries,
    totalEntries: result.totalEntries,
  };
};

// ========================================
// COMPONENT 5 — OFFICIAL ACCOUNTABILITY
// ========================================
//
// Two independent signals about the people who actually hold authority
// over the chama's money, blended when both are present:
//
//   a) Peer rating — the average of every current member rating of
//      every current official (OfficialRating), normalized to 0-100.
//   b) Co-sign compliance — of this chama's RESOLVED high-value
//      approval requests (money actually moved or was formally
//      declined), what fraction had at least MIN_REQUIRED_COSIGNERS
//      independent officials sign off, regardless of what the chama's
//      own ApprovalRequest.required_approvals happened to be set to.
//      This is the "mandatory co-signing threshold" check made
//      concrete and measurable.
//
// ========================================

const computeOfficialAccountability = async (chamaId) => {
  const officials = await ChamaMembership.find({
    chama_id: chamaId,
    status: 'active',
    role: { $in: OFFICIAL_ROLES },
  })
    .select('_id')
    .lean();

  const officialIds = officials.map((o) => o._id);

  // --- (a) peer ratings ---
  const ratings = officialIds.length
    ? await OfficialRating.find({ chama_id: chamaId, official_membership_id: { $in: officialIds } })
        .select('rating')
        .lean()
    : [];

  const avgRating = ratings.length
    ? ratings.reduce((sum, r) => sum + r.rating, 0) / ratings.length
    : null;

  const ratingScore =
    avgRating !== null
      ? Math.round(
          ((avgRating - OFFICIAL_RATING_MIN) / (OFFICIAL_RATING_MAX - OFFICIAL_RATING_MIN)) * 100
        )
      : null;

  // --- (b) co-sign compliance on resolved, high-value requests ---
  const resolvedRequests = await ApprovalRequest.find({
    chama_id: chamaId,
    resource_type: { $in: HIGH_VALUE_COSIGN_RESOURCE_TYPES },
    status: 'approved',
  })
    .select('approvals')
    .lean();

  const totalHighValueRequests = resolvedRequests.length;
  const compliantCount = resolvedRequests.filter((r) => {
    const uniqueApprovers = new Set(
      (r.approvals || [])
        .filter((a) => a.status === 'approved')
        .map((a) => String(a.approver_id))
    );
    return uniqueApprovers.size >= MIN_REQUIRED_COSIGNERS;
  }).length;

  const coSignComplianceRate = totalHighValueRequests
    ? compliantCount / totalHighValueRequests
    : null;
  const coSignScore =
    coSignComplianceRate !== null ? Math.round(coSignComplianceRate * 100) : null;

  // --- blend ---
  const subScores = [ratingScore, coSignScore].filter((s) => s !== null);
  const hasData = subScores.length > 0;
  const score = hasData ? Math.round(subScores.reduce((a, b) => a + b, 0) / subScores.length) : null;

  return {
    hasData,
    score,
    avgRating,
    ratingCount: ratings.length,
    officialCount: officialIds.length,
    coSignComplianceRate,
    compliantCount,
    totalHighValueRequests,
  };
};

// ========================================
// GENERATE (AND PERSIST) A TRUST SCORE SNAPSHOT
// ========================================

export const generateTrustScore = async ({ chamaId, actorUserId, isSystemGenerated = false }) => {
  validateObjectId(chamaId, 'Chama ID');

  const chama = await Chama.findById(chamaId).lean();
  if (!chama) throw new AppError('Chama not found', 404);

  const [repayment, kyc, auditIntegrity] = await Promise.all([
    computeRepaymentReliability(chamaId),
    computeKycCoverage(chamaId),
    computeAuditIntegrity(chamaId),
  ]);

  const [disputes, officialAccountability] = await Promise.all([
    computeDisputeRate(chamaId, kyc.activeMemberCount),
    computeOfficialAccountability(chamaId),
  ]);

  const components = { repayment, kyc, disputes, auditIntegrity, officialAccountability };

  const componentsWithData = Object.keys(components).filter((key) => components[key].hasData);
  const weights = normalizeWeights(componentsWithData);

  const score = componentsWithData.length
    ? Math.round(
        componentsWithData.reduce((sum, key) => sum + components[key].score * weights[key], 0)
      )
    : null;

  const grade = gradeForScore(score);

  const componentsForDoc = {};
  for (const key of Object.keys(components)) {
    componentsForDoc[key] = { ...components[key], weight: weights[key] || 0 };
  }

  const snapshot = await ChamaTrustScore.create({
    chama_id: chamaId,
    generated_by_user_id: isSystemGenerated ? null : actorUserId,
    is_system_generated: isSystemGenerated,
    score,
    grade,
    components: componentsForDoc,
    components_used: componentsWithData,
    chama_snapshot: {
      name: chama.name,
      chama_type: chama.chama_type,
      active_member_count: kyc.activeMemberCount,
      chama_created_at: chama.createdAt,
    },
  });

  await createAuditLog({
    actorUserId,
    isSystemGenerated,
    scopeType: AUDIT_SCOPE_TYPES.CHAMA,
    chamaId,
    action: AUDIT_ACTIONS.TRUST_SCORE_GENERATED,
    resourceType: 'ChamaTrustScore',
    resourceId: snapshot._id,
    after: { score, grade, componentsUsed: componentsWithData },
  });

  return snapshot.toObject();
};

// ========================================
// GET LATEST SNAPSHOT (generating one if none exists yet)
// ========================================

export const getLatestTrustScore = async (chamaId) => {
  validateObjectId(chamaId, 'Chama ID');

  const latest = await ChamaTrustScore.findOne({ chama_id: chamaId })
    .sort({ createdAt: -1 })
    .lean();

  return latest || null;
};

// ========================================
// HISTORY
// ========================================

export const listTrustScoreHistory = async ({ chamaId, page = 1, limit = 12 }) => {
  validateObjectId(chamaId, 'Chama ID');

  const currentPage = Math.max(Number(page) || 1, 1);
  const pageLimit = Math.min(Math.max(Number(limit) || 12, 1), 50);
  const skip = (currentPage - 1) * pageLimit;

  const [snapshots, total] = await Promise.all([
    ChamaTrustScore.find({ chama_id: chamaId })
      .select('score grade createdAt components_used is_public shared_at')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(pageLimit)
      .lean(),
    ChamaTrustScore.countDocuments({ chama_id: chamaId }),
  ]);

  const totalPages = Math.ceil(total / pageLimit) || 1;

  return {
    snapshots,
    pagination: {
      page: currentPage,
      limit: pageLimit,
      total,
      totalPages,
      hasNextPage: currentPage < totalPages,
      hasPreviousPage: currentPage > 1,
    },
  };
};

// ========================================
// SHARE LINK — CREATE
// ========================================

export const createShareLink = async ({ chamaId, trustScoreId, actorUserId }) => {
  validateObjectId(chamaId, 'Chama ID');
  validateObjectId(trustScoreId, 'Trust score ID');

  const snapshot = await ChamaTrustScore.findOne({ _id: trustScoreId, chama_id: chamaId });
  if (!snapshot) throw new AppError('Trust score report not found', 404);

  // Reuse an existing live token rather than minting a new one on every
  // click of "Share" — a bank that already has the link keeps working.
  if (!snapshot.share_token) {
    snapshot.share_token = crypto.randomBytes(24).toString('hex');
  }
  snapshot.is_public = true;
  snapshot.shared_by_user_id = actorUserId;
  snapshot.shared_at = new Date();
  await snapshot.save();

  await createAuditLog({
    actorUserId,
    scopeType: AUDIT_SCOPE_TYPES.CHAMA,
    chamaId,
    action: AUDIT_ACTIONS.TRUST_SCORE_SHARED,
    resourceType: 'ChamaTrustScore',
    resourceId: snapshot._id,
    after: { score: snapshot.score, grade: snapshot.grade },
  });

  return snapshot.toObject();
};

// ========================================
// SHARE LINK — REVOKE
// ========================================

export const revokeShareLink = async ({ chamaId, trustScoreId, actorUserId }) => {
  validateObjectId(chamaId, 'Chama ID');
  validateObjectId(trustScoreId, 'Trust score ID');

  const snapshot = await ChamaTrustScore.findOne({ _id: trustScoreId, chama_id: chamaId });
  if (!snapshot) throw new AppError('Trust score report not found', 404);

  // Clear the token entirely (not just flip is_public) so the old URL
  // can never be replayed even by a bug that flips is_public back.
  snapshot.share_token = null;
  snapshot.is_public = false;
  await snapshot.save();

  await createAuditLog({
    actorUserId,
    scopeType: AUDIT_SCOPE_TYPES.CHAMA,
    chamaId,
    action: AUDIT_ACTIONS.TRUST_SCORE_SHARE_REVOKED,
    resourceType: 'ChamaTrustScore',
    resourceId: snapshot._id,
  });

  return snapshot.toObject();
};

// ========================================
// PUBLIC — GET BY SHARE TOKEN
// ========================================
//
// No auth. Returns only what a bank/SACCO federation needs to evaluate
// the chama — the score, its breakdown, and denormalized chama facts —
// never member names, official identities, dispute content, or raw
// rating comments.
//
// ========================================

export const getPublicTrustScoreByToken = async (token) => {
  if (!token || typeof token !== 'string') {
    throw new AppError('Trust score report not found', 404);
  }

  const snapshot = await ChamaTrustScore.findOne({ share_token: token, is_public: true }).lean();
  if (!snapshot) {
    throw new AppError('This trust score link is invalid or has been revoked', 404);
  }

  return {
    chama: snapshot.chama_snapshot,
    score: snapshot.score,
    grade: snapshot.grade,
    componentsUsed: snapshot.components_used,
    components: snapshot.components,
    generatedAt: snapshot.createdAt,
    sharedAt: snapshot.shared_at,
  };
};