import ChamaLoan from '../../models/ChamaLoan.js';
import AppError from '../../utils/AppError.js';
import { getOrCreatePolicy } from './Loanpolicy.service.js';
import { getMemberSavings } from './loanSavings.service.js';
import loanRepayment from './Loanrepayment.service.js';
const outstanding = (loan) => Number(loan.balances?.principal_outstanding || 0) + Number(loan.balances?.interest_outstanding || 0) + Number(loan.balances?.penalty_outstanding || 0);
export async function initiateRecovery({ chama, loanId }) { const loan = await ChamaLoan.findOne({ _id: loanId, chama_id: chama._id }); if (!loan) throw new AppError('Loan not found', 404); if (loan.status !== 'defaulted') throw new AppError('Only a defaulted loan can enter recovery', 400); if (!(await getOrCreatePolicy(chama._id)).allow_guarantor_recovery) throw new AppError('Guarantor recovery is disabled by this Chama policy', 400); loan.default_info.recovery_status = 'notice_sent'; loan.default_info.recovery_notice_sent_at = new Date(); await loan.save(); return loan; }
export async function recoverFromGuarantors({ chama, loanId, userId }) { let loan = await ChamaLoan.findOne({ _id: loanId, chama_id: chama._id }); if (!loan) throw new AppError('Loan not found', 404); if (loan.status !== 'defaulted') throw new AppError('Only a defaulted loan can be recovered from guarantors', 400); if (!(await getOrCreatePolicy(chama._id)).allow_guarantor_recovery) throw new AppError('Guarantor recovery is disabled by this Chama policy', 400); const payments=[]; for (const guarantor of loan.guarantors.filter((g)=>g.status==='accepted')) { const amount=Math.min(outstanding(loan), Math.max(0, Number(guarantor.guaranteed_amount)-Number(guarantor.recovered_amount||0)), await getMemberSavings(chama._id, guarantor.membership_id)); if(amount<=0) continue; const result=await loanRepayment.recordRepayment({chama,loanId:loan._id,amount,source:'guarantor_recovery',externalReference:`GUAR-${loan.reference}`,recordedBy:userId,membershipIdOverride:guarantor.membership_id}); guarantor.recovered_amount=Number(guarantor.recovered_amount||0)+amount; loan=result.loan; payments.push(result.payment); if(loan.status==='closed') break; } loan.default_info.recovery_status=loan.status==='closed'?'recovered':'in_recovery'; if(loan.status==='closed') loan.status='recovered'; await loan.save(); return {loan,payments}; }
export default { initiateRecovery, recoverFromGuarantors };
