import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, BrainCircuit, CheckCircle2, Clock3, Landmark, MonitorSmartphone, ScaleIcon, ShieldAlert, ShieldCheck, Siren, TriangleAlert, UserRoundX } from 'lucide-react';
import securityService from '../services/security.service';
import Spinner from '@/shared/components/ui/Spinner';

const severityStyle = { CRITICAL: 'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300', HIGH: 'bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300', MEDIUM: 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300', LOW: 'bg-sky-100 text-sky-700 dark:bg-sky-950 dark:text-sky-300' };
const tintStyle = { emerald: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950', orange: 'bg-orange-100 text-orange-700 dark:bg-orange-950', rose: 'bg-rose-100 text-rose-700 dark:bg-rose-950' };
const dateTime = (value) => value ? new Intl.DateTimeFormat('en-KE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';

export default function SecurityCommandCenterPage() {
  const [center, setCenter] = useState(null); const [riskSignals, setRiskSignals] = useState(null); const [alerts, setAlerts] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
  const load = async () => {
    setError(null);
    try {
      const [nextCenter, nextSignals, nextAlerts] = await Promise.all([securityService.getCommandCenter(), securityService.getRiskSignals(), securityService.getAlerts({ status: 'OPEN' })]);
      setCenter(nextCenter); setRiskSignals(nextSignals); setAlerts(nextAlerts);
      setSelected((current) => nextAlerts.find((a) => a._id === current?._id) || nextAlerts[0] || null);
    } catch (err) {
      // Previously a rejection here (403 from requireAdminPermission,
      // a 5xx, etc.) silently left center/riskSignals/alerts at their
      // initial null/[] state, so every card fell back to its `?? 0`
      // default — a dashboard full of zeros that looked identical to
      // "nothing detected". Surface it instead of hiding it.
      console.error('Security Command Center failed to load', err);
      setError(err?.response?.data?.message || err?.message || 'Failed to load security data.');
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => { load(); }, []);
  const respond = async (id, action) => { await securityService.respond(id, action); await load(); };
  if (loading) return <Spinner />;
  if (error) return <div className="rounded-3xl border border-rose-200 bg-rose-50 p-6 text-sm font-bold text-rose-700 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-300">Couldn't load the Security Command Center: {error}<button onClick={load} className="ml-3 underline">Retry</button></div>;
  const cards = [{ label: 'Platform trust', value: `${center?.platformTrust ?? 100}%`, icon: ShieldCheck, tint: 'emerald' }, { label: 'Active threats', value: center?.activeThreats ?? 0, icon: ShieldAlert, tint: 'orange' }, { label: 'Open incidents', value: center?.incidents ?? 0, icon: Siren, tint: 'rose' }];
  const signalCards = [
    { label: 'Failed logins', value: riskSignals?.failedLogins?.total ?? 0, detail: `${riskSignals?.failedLogins?.otpFailures ?? 0} OTP failures`, icon: UserRoundX },
    { label: 'Velocity anomalies', value: riskSignals?.velocityEvents?.length ?? 0, detail: `${riskSignals?.velocityAnomalies?.length ?? 0} high-volume IPs`, icon: Activity },
    { label: 'Flagged transactions', value: riskSignals?.flaggedTransactions?.length ?? 0, detail: 'Monitor or hold decisions', icon: Landmark },
    { label: 'Device / IP anomalies', value: riskSignals?.deviceIpAnomalies?.length ?? 0, detail: 'New or unknown origin', icon: MonitorSmartphone },
    { label: 'Unbalanced ledgers', value: riskSignals?.ledgerIntegrity?.total ?? 0, detail: 'Debits vs credits mismatch', icon: ScaleIcon },
  ];
  return <div className="space-y-7">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-r from-slate-950 via-slate-900 to-indigo-950 p-7 text-white shadow-xl">
      <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-cyan-300"><BrainCircuit size={16}/> TrustOS · Continuous intelligence</div><h1 className="text-3xl font-black tracking-tight">Security Command Center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Live, explainable intelligence from platform telemetry. Decisions are policy-driven; the controls below remain human-governed.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm text-cyan-100"><span className="font-bold">Coverage:</span> {Object.values(center?.coverage || {}).filter(Boolean).length}/4 monitored domains</div></div>
    </section>
    <section className="grid gap-4 md:grid-cols-3">{cards.map(({ label, value, icon: Icon, tint }) => <div key={label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between text-sm font-bold text-slate-500"><span>{label}</span><div className={`rounded-xl p-2 ${tintStyle[tint]}`}><Icon size={18}/></div></div><div className="mt-5 text-3xl font-black text-slate-950 dark:text-white">{value}</div></div>)}</section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-black text-slate-950 dark:text-white"><TriangleAlert className="text-amber-500" size={20}/> Risk signals</h2><p className="mt-1 text-sm text-slate-500">Whole-system investigation view for the last {riskSignals?.window?.hours ?? 24} hours. Signals are grouped from scored telemetry, not inferred from audit access.</p></div><span className="text-xs text-slate-400">Updated {dateTime(riskSignals?.window?.until)}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{signalCards.map(({ label, value, detail, icon: Icon }) => <div key={label} className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800"><Icon size={18} className="text-indigo-600"/><div className="mt-4 text-2xl font-black text-slate-950 dark:text-white">{value}</div><div className="mt-1 text-sm font-bold text-slate-700 dark:text-slate-200">{label}</div><div className="mt-1 text-xs text-slate-500">{detail}</div></div>)}</div></section>
    <section className="grid gap-6 xl:grid-cols-2"><SignalList title="Velocity & credential anomalies" empty="No credential bursts or high-frequency activity in this window." items={[...(riskSignals?.velocityEvents || []), ...(riskSignals?.velocityAnomalies || [])]} render={(item) => <><div className="font-bold text-slate-900 dark:text-white">{item.ip || item.eventType?.replaceAll('_', ' ') || 'Velocity anomaly'}</div><div className="mt-1 text-xs text-slate-500">{item.eventCount ? `${item.eventCount} events · ${item.distinctActors} accounts` : `${item.decision} · risk ${item.riskScore}/100`} · {dateTime(item.lastSeen || item.createdAt)}</div></>} /><SignalList title="Flagged transactions" empty="No risky financial events were observed." items={riskSignals?.flaggedTransactions || []} render={(item) => <><div className="font-bold text-slate-900 dark:text-white">{item.eventType?.replaceAll('_', ' ') || 'Transaction'} · KES {Number(item.transaction?.amount || 0).toLocaleString()}</div><div className="mt-1 text-xs text-slate-500">{item.decision} · risk {item.riskScore}/100 · {dateTime(item.createdAt)}</div></>} /><SignalList title="Device & network anomalies" empty="No new or unknown device/network activity was observed." items={riskSignals?.deviceIpAnomalies || []} render={(item) => <><div className="font-bold text-slate-900 dark:text-white">{item.device?.deviceId || item.network?.ip || item.eventType?.replaceAll('_', ' ')}</div><div className="mt-1 text-xs text-slate-500">Risk {item.riskScore}/100 · {item.signals?.map((signal) => signal.code).join(', ')} · {dateTime(item.createdAt)}</div></>} /><SignalList title="Elevated trust profiles" empty="No users currently have an elevated trust state." items={riskSignals?.riskyProfiles || []} render={(item) => <><div className="font-bold text-slate-900 dark:text-white">{item.entityType} {item.entityId}</div><div className="mt-1 text-xs text-slate-500">{item.trustState} · risk {item.riskScore}/100 · last event {dateTime(item.lastEventAt)}</div></>} /><SignalList title="Ledger integrity" empty="No ledger imbalances detected." items={riskSignals?.ledgerIntegrity?.unbalancedOwners || []} render={(item) => <><div className="font-bold text-slate-900 dark:text-white">{item.ownerType} {item.ownerId}</div><div className="mt-1 text-xs text-slate-500">Debits KES {item.totalDebits?.toLocaleString()} · Credits KES {item.totalCredits?.toLocaleString()} · diff KES {item.difference?.toLocaleString()}</div></>} /></section>
    <section className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b border-slate-100 p-6 dark:border-slate-800"><h2 className="flex items-center gap-2 text-lg font-black text-slate-950 dark:text-white"><AlertTriangle className="text-rose-500" size={20}/> Active security alerts</h2><p className="mt-1 text-sm text-slate-500">Select an alert to see the evidence and recommended control.</p></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{alerts.length ? alerts.map((alert) => <button key={alert._id} onClick={() => setSelected(alert)} className={`w-full p-5 text-left transition hover:bg-slate-50 dark:hover:bg-slate-800/60 ${selected?._id === alert._id ? 'bg-indigo-50/70 dark:bg-indigo-950/30' : ''}`}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${severityStyle[alert.severity]}`}>{alert.severity}</span><span className="text-xs text-slate-500">Risk {alert.riskScore}/100</span></div><h3 className="mt-2 font-bold capitalize text-slate-900 dark:text-white">{alert.title}</h3><p className="mt-1 line-clamp-1 text-sm text-slate-500">{alert.explanation?.summary}</p></div><span className="whitespace-nowrap text-xs text-slate-400">{dateTime(alert.createdAt)}</span></div></button>) : <div className="p-10 text-center text-sm text-slate-500"><CheckCircle2 className="mx-auto mb-3 text-emerald-500"/>No active alerts. Telemetry will appear here as it is evaluated.</div>}</div></div>
      <aside className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">{selected ? <><div className="flex items-center justify-between"><h2 className="text-lg font-black text-slate-950 dark:text-white">Explain why</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${severityStyle[selected.severity]}`}>{selected.severity}</span></div><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{selected.explanation?.summary}</p><div className="mt-5 space-y-3">{selected.explanation?.signals?.map((signal) => <div key={signal.code} className="rounded-2xl bg-slate-50 p-3 dark:bg-slate-800"><div className="flex items-center justify-between gap-3 text-sm font-bold text-slate-800 dark:text-slate-100"><span>{signal.label}</span><span className="text-rose-600">+{signal.contribution}</span></div><div className="mt-1 text-xs text-slate-500">{signal.code} · {signal.confidence} confidence</div></div>)}</div><div className="mt-5 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-950 dark:border-indigo-900 dark:bg-indigo-950/40 dark:text-indigo-100"><strong>Recommended control:</strong><br/>{selected.explanation?.recommendedControl}</div><div className="mt-5 flex gap-3"><button onClick={() => respond(selected._id, 'acknowledge')} className="flex-1 rounded-xl bg-slate-900 px-3 py-2.5 text-xs font-bold text-white hover:bg-slate-700">Acknowledge</button><button onClick={() => respond(selected._id, 'resolve')} className="flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200">Resolve</button></div></> : <div className="py-12 text-center text-sm text-slate-500"><Clock3 className="mx-auto mb-3"/>Select an alert to inspect its security story.</div>}</aside></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-black text-slate-950 dark:text-white">Live security timeline</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(center?.recentEvents || []).map((event) => <div key={event._id} className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800"><div className="text-xs font-black text-indigo-600">{event.eventType}</div><div className="mt-2 text-sm font-bold text-slate-800 dark:text-slate-100">Decision: {event.decision} · Risk {event.riskScore}</div><div className="mt-1 text-xs text-slate-500">{dateTime(event.createdAt)}</div></div>)}</div></section>
  </div>;
}

function SignalList({ title, empty, items, render }) {
  return <div className="rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b border-slate-100 p-5 dark:border-slate-800"><h2 className="font-black text-slate-950 dark:text-white">{title}</h2></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{items.length ? items.slice(0, 8).map((item, index) => <div key={item._id || item.ip || `${title}-${index}`} className="p-4">{render(item)}</div>) : <div className="p-6 text-sm text-slate-500">{empty}</div>}</div></div>;
}