import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import chamaApi from "../api/chama.api";

const initialProfile = { contribution_cycle: "monthly", fine_amount: 0, meeting_day: "", approval_threshold: 20000, required_payout_approvals: 2, mpesa_shortcode: "", bank_name: "", bank_account_number: "", constitution_url: "" };
export default function ChamaCommandCenterPage() {
  const { workspaceId } = useParams(); const [data, setData] = useState(null); const [profile, setProfile] = useState(initialProfile); const [notice, setNotice] = useState("");
  const load = async () => { try { const response = await chamaApi.getCommandCenter(workspaceId); setData(response.data.data); setProfile((current) => ({ ...current, ...(response.data.data.profile || {}) })); } catch (error) { setNotice(error?.response?.data?.message || "Could not load Chama operations."); } };
  useEffect(() => { load(); }, [workspaceId]);
  const run = async (action, message) => { try { await action(); setNotice(message); await load(); } catch (error) { setNotice(error?.response?.data?.message || error.message || "Action failed."); } };
  if (!data) return <div className="p-6">Loading Chama command center…</div>;
  const official = ["chairperson", "treasurer", "secretary"].includes(data.membership.role);
  return <div className="mx-auto max-w-6xl space-y-6"><header><h1 className="text-3xl font-bold">Chama Command Center</h1><p className="text-slate-500">Governance, treasury controls, loan approvals, KYC and meeting records.</p></header>{notice && <div className="rounded-xl border bg-slate-50 p-3 text-sm">{notice}</div>}<div className="grid gap-6 lg:grid-cols-2">
    <Panel title="Rules & treasury setup"><form className="grid gap-3" onSubmit={(e) => { e.preventDefault(); run(() => chamaApi.saveProfile(workspaceId, profile), "Chama settings saved."); }}><Select label="Contribution cycle" value={profile.contribution_cycle} onChange={(v) => setProfile({ ...profile, contribution_cycle: v })} options={["weekly", "monthly", "quarterly"]}/><Input label="Constitution document URL" value={profile.constitution_url || ""} onChange={(v) => setProfile({ ...profile, constitution_url: v })}/><Input label="Fine (KES)" type="number" value={profile.fine_amount ?? 0} onChange={(v) => setProfile({ ...profile, fine_amount: v })}/><Input label="Meeting day" value={profile.meeting_day || ""} onChange={(v) => setProfile({ ...profile, meeting_day: v })}/><Input label="M-Pesa Till / Paybill" value={profile.mpesa_shortcode || ""} onChange={(v) => setProfile({ ...profile, mpesa_shortcode: v })}/><Input label="Bank name" value={profile.bank_name || ""} onChange={(v) => setProfile({ ...profile, bank_name: v })}/><Input label="Bank account number" value={profile.bank_account_number || ""} onChange={(v) => setProfile({ ...profile, bank_account_number: v })}/>{official && <button className="button">Save governance settings</button>}</form></Panel>
    <Panel title="Goals"><GoalForm onSubmit={(payload) => run(() => chamaApi.addGoal(workspaceId, payload), "Goal created.")}/><div className="mt-4 space-y-2">{data.goals.map((goal) => <div key={goal._id} className="rounded-lg border p-3"><b>{goal.name}</b><span className="float-right">KES {Number(goal.saved_amount || 0).toLocaleString()} / {Number(goal.target_amount).toLocaleString()}</span></div>)}</div></Panel>
    <Panel title="Loan application & approvals"><LoanForm onSubmit={(payload) => run(() => chamaApi.applyLoan(workspaceId, payload), "Loan eligibility checked and application recorded.")}/><div className="mt-4 space-y-2">{data.loans.map((loan) => <div key={loan._id} className="rounded-lg border p-3"><b>KES {Number(loan.amount).toLocaleString()}</b> — {loan.purpose}<span className="ml-2 text-sm">{loan.status}</span>{official && loan.status === "eligible" && <button onClick={() => run(() => chamaApi.approveLoan(workspaceId, loan._id), "Approval recorded.")} className="ml-3 text-sm underline">Approve</button>}{data.membership.role === "treasurer" && loan.status === "approved" && <button onClick={() => run(() => chamaApi.disburseLoan(workspaceId, loan._id), "B2C disbursement submitted.")} className="ml-3 text-sm underline">Send B2C</button>}</div>)}</div></Panel>
    <Panel title="KYC & digital member card"><KycForm onSubmit={(payload) => run(() => chamaApi.submitKyc(workspaceId, payload), "KYC submitted for chair review.")}/><p className="mt-3 text-sm">KYC: <b>{data.kyc?.status || "not submitted"}</b></p><div className="mt-3 rounded-xl bg-emerald-700 p-4 text-white"><p className="text-xs">DIGITAL CHAMA MEMBER CARD</p><b>{data.membership.role.toUpperCase()}</b><p>Member ID: {String(data.membership._id).slice(-8).toUpperCase()}</p></div></Panel>
    <Panel title="Live meeting, attendance & minutes"><MeetingForm onSubmit={(payload) => run(() => chamaApi.createMeetingRecord(workspaceId, payload), "Live meeting started.")}/>{data.meetings.map((meeting) => <div key={meeting._id} className="mt-3 rounded-lg border p-3"><b>{meeting.title}</b> — {meeting.status}<button onClick={() => run(() => chamaApi.checkInMeeting(workspaceId, meeting._id), "Attendance recorded.")} className="ml-3 text-sm underline">QR/check-in</button>{official && <button onClick={() => run(() => chamaApi.saveMeetingRecord(workspaceId, meeting._id, { close: true }), "Meeting closed and vote resolutions saved.")} className="ml-3 text-sm underline">Close & save resolutions</button>}</div>)}</Panel>
    <Panel title="Officials & invitations"><div className="space-y-2">{data.officials.map((member) => <div key={member._id} className="rounded-lg border p-3">{member.user_id?.name || "Official"} <span className="float-right">{member.role}</span></div>)}</div>{data.membership.role === "chairperson" && <OfficialForm members={data.members} onSubmit={({ membershipId, role }) => run(() => chamaApi.assignOfficial(workspaceId, membershipId, role), "Official role updated.")}/>}<InviteForm onSubmit={(payload) => run(async () => { const result = await chamaApi.createInvitation(workspaceId, payload); setNotice(`Invitation created: ${result.data.data.join_path}`); }, "Invitation created.")}/></Panel>
  </div></div>;
}
function Panel({ title, children }) { return <section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="mb-4 text-lg font-bold">{title}</h2>{children}</section>; }
function Input({ label, value, onChange, type = "text" }) { return <label className="text-sm">{label}<input className="mt-1 w-full rounded-lg border p-2" type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Select({ label, value, onChange, options }) { return <label className="text-sm">{label}<select className="mt-1 w-full rounded-lg border p-2" value={value} onChange={(e) => onChange(e.target.value)}>{options.map((o) => <option key={o}>{o}</option>)}</select></label>; }
function GoalForm({ onSubmit }) { const [name, setName] = useState(""); const [target_amount, setTarget] = useState(""); return <form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); onSubmit({ name, target_amount: Number(target_amount) }); }}><input required placeholder="Land Fund" className="min-w-0 flex-1 rounded-lg border p-2" value={name} onChange={(e) => setName(e.target.value)}/><input required type="number" placeholder="2,000,000" className="w-32 rounded-lg border p-2" value={target_amount} onChange={(e) => setTarget(e.target.value)}/><button className="button">Add</button></form>; }
function LoanForm({ onSubmit }) { const [form, setForm] = useState({ amount: "", purpose: "", phone_number: "", savings_balance: "", savings_months: "" }); return <form className="grid gap-2" onSubmit={(e) => { e.preventDefault(); onSubmit({ ...form, amount: Number(form.amount), savings_balance: Number(form.savings_balance), savings_months: Number(form.savings_months) }); }}><Input label="Amount" type="number" value={form.amount} onChange={(v) => setForm({ ...form, amount: v })}/><Input label="Purpose" value={form.purpose} onChange={(v) => setForm({ ...form, purpose: v })}/><Input label="M-Pesa phone" value={form.phone_number} onChange={(v) => setForm({ ...form, phone_number: v })}/><Input label="Savings balance" type="number" value={form.savings_balance} onChange={(v) => setForm({ ...form, savings_balance: v })}/><Input label="Months contributing" type="number" value={form.savings_months} onChange={(v) => setForm({ ...form, savings_months: v })}/><button className="button">Check eligibility & apply</button></form>; }
function KycForm({ onSubmit }) { const [form, setForm] = useState({ id_number: "", id_document_url: "", selfie_url: "" }); return <form className="grid gap-2" onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}><Input label="National ID number" value={form.id_number} onChange={(v) => setForm({ ...form, id_number: v })}/><Input label="ID document URL" value={form.id_document_url} onChange={(v) => setForm({ ...form, id_document_url: v })}/><Input label="Selfie URL" value={form.selfie_url} onChange={(v) => setForm({ ...form, selfie_url: v })}/><button className="button">Submit KYC</button></form>; }
function MeetingForm({ onSubmit }) { const [title, setTitle] = useState(""); return <form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); onSubmit({ title }); }}><input required className="min-w-0 flex-1 rounded-lg border p-2" placeholder="August monthly meeting" value={title} onChange={(e) => setTitle(e.target.value)}/><button className="button">Start meeting</button></form>; }
function OfficialForm({ members, onSubmit }) { const [membershipId, setId] = useState(""); const [role, setRole] = useState("treasurer"); return <form className="mt-4 flex flex-wrap gap-2" onSubmit={(e) => { e.preventDefault(); onSubmit({ membershipId, role }); }}><select required className="rounded-lg border p-2" value={membershipId} onChange={(e) => setId(e.target.value)}><option value="">Select member</option>{members.map((member) => <option key={member._id} value={member._id}>{member.user_id?.name || member._id}</option>)}</select><select className="rounded-lg border p-2" value={role} onChange={(e) => setRole(e.target.value)}>{["chairperson", "treasurer", "secretary"].map((item) => <option key={item}>{item}</option>)}</select><button className="button">Set official</button></form>; }
function InviteForm({ onSubmit }) { const [phone, setPhone] = useState(""); return <form className="mt-4 flex gap-2" onSubmit={(e) => { e.preventDefault(); onSubmit({ phone }); }}><input required className="min-w-0 flex-1 rounded-lg border p-2" placeholder="Member phone number" value={phone} onChange={(e) => setPhone(e.target.value)}/><button className="button">Create invite link</button></form>; }
