/**
 * Default Seed Dataset: 14 Realistic Kenyan Rental Properties
 * Styled for high-fidelity property portal experiences matching modern real-estate UI.
 */

export const DEFAULT_RENTAL_PROPERTIES = [
  {
    title: "Argwings Luxury 2BR Executive Penthouse",
    slug: "argwings-luxury-2br-executive-penthouse",
    subcategory: "apartments",
    price: 85000,
    compare_price: 95000,
    short_description: "Designer 2-bedroom executive penthouse with panoramic Kilimani skyline views, European finishes, and dual balconies.",
    description: `Experience elevated urban living in this sun-drenched 2-bedroom executive penthouse on Argwings Kodhek Road. Crafted with floor-to-ceiling soundproof glass, open-concept living and dining spaces, and an expansive covered sunset terrace.

Features include a chef's kitchen with built-in Bosch appliances, quartz countertops, high-speed fiber internet, full-load backup generator, heated rooftop swimming pool, and fully equipped gym. The master suite features a walk-in wardrobe and an en-suite spa bathroom with Italian rainfall shower.`,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Pets allowed", "Modern interior", "Exclusive", "Balcony", "Pool"],
    is_featured: true,
    featured_rank: 1,
    rating: 4.9,
    review_count: 42,
    rental_attributes: {
      listing_type: "apartment",
      property_type: "Penthouse",
      bedrooms: 2,
      bathrooms: 2,
      rent_period: "month",
      deposit_amount: 85000,
      area_sqm: 110,
      floor: "8/10",
      year_built: 2023,
      pets_allowed: true,
      parking_spaces: 2,
      furnished: true,
      amenities: [
        "High-Speed Fiber WiFi",
        "Full Backup Generator",
        "Borehole Water Backup",
        "Rooftop Swimming Pool",
        "24/7 CCTV & Security",
        "High-Speed Elevator",
        "Equipped Gym",
        "Solar Water Heating",
      ],
      location_text: "Argwings Kodhek Rd, Kilimani, Nairobi",
      address: "Argwings Kodhek Road, Penthouse 8B",
      city: "Nairobi",
      neighborhood: "Kilimani",
      coordinates: { lat: -1.2975, lng: 36.7865 },
      agent: {
        name: "Alaya Saunders",
        role: "Senior Leasing Partner",
        phone: "+254712345678",
        whatsapp: "+254712345678",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.9,
        reviews_count: 112,
        experience_years: 6,
        active_ads_count: 14,
      },
      room_breakdown: [
        {
          room_name: "/Planning",
          image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
          area_sqm: 110,
          description: "Dual-balcony architectural layout with separate dining and entertaining wings.",
        },
        {
          room_name: "/Kitchen-living room",
          image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
          area_sqm: 48,
          description: "Designer open kitchen with custom cabinetry, quartz waterfall island, and wine fridge.",
        },
        {
          room_name: "/Master bedroom",
          image_url: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80",
          area_sqm: 32,
          description: "King-sized master suite with floor-to-ceiling glass and walk-in wardrobe.",
        },
        {
          room_name: "/Bathroom",
          image_url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
          area_sqm: 14,
          description: "Marble tiled bathroom with frameless glass rainfall shower and vanity mirrors.",
        },
      ],
    },
  },
  {
    title: "Westlands Skyview Executive Studio & Bedsitter",
    slug: "westlands-skyview-executive-studio",
    subcategory: "rooms",
    price: 32000,
    compare_price: 36000,
    short_description: "Furnished high-floor studio in the center of Westlands with city views, biometric access, and rooftop terrace.",
    description: `Perfect for young executives and expats. This ultra-modern studio apartment in Westlands features custom storage solutions, integrated kitchenette, smart keyless entry, and access to a shared lounge and rooftop work pod. Located within walking distance to Sarit Centre and Westgate.`,
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Furnished", "City view", "Bedsitter", "Near Transit"],
    is_featured: true,
    featured_rank: 2,
    rating: 4.8,
    review_count: 28,
    rental_attributes: {
      listing_type: "room",
      property_type: "Bedsitter / Studio",
      bedrooms: 0,
      bathrooms: 1,
      rent_period: "month",
      deposit_amount: 32000,
      area_sqm: 42,
      floor: "12/16",
      year_built: 2022,
      pets_allowed: false,
      parking_spaces: 1,
      furnished: true,
      amenities: [
        "High-Speed Fiber WiFi",
        "Biometric Security",
        "Rooftop Work Pods",
        "Borehole Water Backup",
        "High-Speed Lifts",
        "Laundry Facility On-site",
      ],
      location_text: "Mpaka Rd, Westlands, Nairobi",
      address: "Mpaka Road, Skyview Tower Apt 1204",
      city: "Nairobi",
      neighborhood: "Westlands",
      coordinates: { lat: -1.2652, lng: 36.8044 },
      agent: {
        name: "David Kimani",
        role: "Westlands Leasing Lead",
        phone: "+254722998877",
        whatsapp: "+254722998877",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.8,
        reviews_count: 54,
        experience_years: 4,
        active_ads_count: 8,
      },
      room_breakdown: [
        {
          room_name: "/Studio Suite",
          image_url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
          area_sqm: 32,
          description: "Combined living and bedroom zone with ergonomic study desk and floor-to-ceiling window.",
        },
        {
          room_name: "/Kitchenette",
          image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
          area_sqm: 6,
          description: "Compact kitchen fitted with microwave, induction cooktop, and under-counter fridge.",
        },
        {
          room_name: "/En-suite Bath",
          image_url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
          area_sqm: 4,
          description: "Modern bath with instant instant heating shower and chrome accessories.",
        },
      ],
    },
  },
  {
    title: "Karen Forest Haven 4BR Gated Villa",
    slug: "karen-forest-haven-4br-gated-villa",
    subcategory: "houses",
    price: 240000,
    compare_price: 260000,
    short_description: "Sprawling 4-bedroom standalone home set on 0.5 acres with lush landscaped gardens, DSQ, and solar heating.",
    description: `Nestled in the prestigious Mbagathi Ridge enclave of Karen, this colonial-inspired 4-bedroom villa provides privacy and tranquility. Boasting solid mahogany hardwood flooring, cathedral ceilings, two wood-burning fireplaces, and an expansive covered verandah overlooking mature indigenous trees.`,
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Exclusive", "Pets allowed", "Private Garden", "Swimming Pool"],
    is_featured: true,
    featured_rank: 3,
    rating: 5.0,
    review_count: 19,
    rental_attributes: {
      listing_type: "house",
      property_type: "Villa",
      bedrooms: 4,
      bathrooms: 4,
      rent_period: "month",
      deposit_amount: 480000,
      area_sqm: 420,
      floor: "2 Storey",
      year_built: 2021,
      pets_allowed: true,
      parking_spaces: 4,
      furnished: false,
      amenities: [
        "0.5 Acre Private Garden",
        "Detached DSQ for 2",
        "Solar Water Heating System",
        "Electric Perimeter Fence",
        "24/7 Gated Community Security",
        "Wood Fireplace",
        "Generator Back-up",
      ],
      location_text: "Mbagathi Ridge, Karen, Nairobi",
      address: "Mbagathi Ridge, Gate 14",
      city: "Nairobi",
      neighborhood: "Karen",
      coordinates: { lat: -1.3324, lng: 36.7118 },
      agent: {
        name: "Grace Mwangi",
        role: "Luxury Estates Director",
        phone: "+254733445566",
        whatsapp: "+254733445566",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 5.0,
        reviews_count: 89,
        experience_years: 9,
        active_ads_count: 18,
      },
      room_breakdown: [
        {
          room_name: "/Exterior Grounds",
          image_url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
          area_sqm: 2000,
          description: "Private manicured lawn with mature trees and outdoor barbecue pergola.",
        },
        {
          room_name: "/Living Room",
          image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
          area_sqm: 75,
          description: "Double-height sunken lounge with stone fireplace and garden views.",
        },
        {
          room_name: "/Master Suite",
          image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
          area_sqm: 55,
          description: "Upper floor master bedroom with balcony terrace and ensuite Jacuzzi bath.",
        },
      ],
    },
  },
  {
    title: "Kileleshwa Riverside Modern 3BR Apartment",
    slug: "kileleshwa-riverside-modern-3br-apartment",
    subcategory: "apartments",
    price: 110000,
    compare_price: 120000,
    short_description: "Chic 3-bedroom master ensuite apartment with serene river valley views, gym, heated pool, and borehole water.",
    description: `A peaceful sanctuary in the heart of Kileleshwa along Riverside. Featuring spacious ensuite bedrooms, open plan living, high speed elevators, kids play park, heated pool, and 24/7 security.`,
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Pets allowed", "Modern interior", "Gym & Pool"],
    is_featured: false,
    rating: 4.7,
    review_count: 15,
    rental_attributes: {
      listing_type: "apartment",
      property_type: "Apartment",
      bedrooms: 3,
      bathrooms: 3,
      rent_period: "month",
      deposit_amount: 110000,
      area_sqm: 165,
      floor: "5/12",
      year_built: 2022,
      pets_allowed: true,
      parking_spaces: 2,
      furnished: false,
      amenities: ["Heated Swimming Pool", "Equipped Gym", "Borehole Water", "Kids Play Area", "Backup Generator", "CCTV"],
      location_text: "Riverside Drive, Kileleshwa, Nairobi",
      address: "Riverside Gardens Block C",
      city: "Nairobi",
      neighborhood: "Kileleshwa",
      coordinates: { lat: -1.2825, lng: 36.7885 },
      agent: {
        name: "Alaya Saunders",
        role: "Senior Leasing Partner",
        phone: "+254712345678",
        whatsapp: "+254712345678",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.9,
        reviews_count: 112,
        experience_years: 6,
        active_ads_count: 14,
      },
    },
  },
  {
    title: "Ruaka Heights Cozy Affordable 1BR",
    slug: "ruaka-heights-cozy-affordable-1br",
    subcategory: "apartments",
    price: 22000,
    compare_price: 24000,
    short_description: "Clean, spacious 1-bedroom apartment near Two Rivers Mall with private balcony, constant water supply, and high-speed lifts.",
    description: `Conveniently situated 5 minutes from Two Rivers Mall and Limuru Road. Features tiled flooring throughout, built-in kitchen cabinets, instant shower, balcony with clothes line, and secure card access.`,
    images: [
      "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Affordable", "Borehole Water", "Fibre Internet"],
    is_featured: false,
    rating: 4.6,
    review_count: 31,
    rental_attributes: {
      listing_type: "apartment",
      property_type: "Apartment",
      bedrooms: 1,
      bathrooms: 1,
      rent_period: "month",
      deposit_amount: 22000,
      area_sqm: 52,
      floor: "3/6",
      year_built: 2021,
      pets_allowed: false,
      parking_spaces: 1,
      furnished: false,
      amenities: ["Borehole Water 24/7", "Fibre WiFi Ready", "CCTV Surveillance", "Elevator", "Rooftop Drying Area"],
      location_text: "Limuru Rd, Ruaka, Nairobi",
      address: "Ruaka Heights Apt 3C",
      city: "Nairobi",
      neighborhood: "Ruaka",
      coordinates: { lat: -1.2052, lng: 36.7761 },
      agent: {
        name: "David Kimani",
        role: "Leasing Specialist",
        phone: "+254722998877",
        whatsapp: "+254722998877",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.8,
        reviews_count: 54,
        experience_years: 4,
        active_ads_count: 8,
      },
    },
  },
  {
    title: "Upper Hill Prime Commercial Office Suite",
    slug: "upper-hill-prime-commercial-office-suite",
    subcategory: "commercial",
    price: 145000,
    compare_price: 160000,
    short_description: "Grade-A 180 sqm commercial office space in Upper Hill financial hub with raised flooring, central AC, and 3 reserved parking bays.",
    description: `High-visibility corporate office suite in a Grade-A business tower. Fully partitioned with executive boardroom, two director offices, open bullpen for 16 staff, and private kitchenette. Backup generators, high speed lifts, and 24/7 access control.`,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    tags: ["Commercial", "Verified", "Fibre Ready", "High-speed Lifts"],
    is_featured: false,
    rating: 4.9,
    review_count: 11,
    rental_attributes: {
      listing_type: "commercial",
      property_type: "Commercial Office",
      bedrooms: 0,
      bathrooms: 2,
      rent_period: "month",
      deposit_amount: 290000,
      area_sqm: 180,
      floor: "7/14",
      year_built: 2020,
      pets_allowed: false,
      parking_spaces: 3,
      furnished: false,
      amenities: ["Grade-A Finishes", "Central Air Conditioning", "Triple High-Speed Lifts", "Full Generator Backup", "24/7 Security"],
      location_text: "Hospital Rd, Upper Hill, Nairobi",
      address: "Upper Hill Commercial Plaza Floor 7",
      city: "Nairobi",
      neighborhood: "Upper Hill",
      coordinates: { lat: -1.2989, lng: 36.8155 },
      agent: {
        name: "Grace Mwangi",
        role: "Commercial Property Director",
        phone: "+254733445566",
        whatsapp: "+254733445566",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 5.0,
        reviews_count: 89,
        experience_years: 9,
        active_ads_count: 18,
      },
    },
  },
  {
    title: "Lavington Greenery 3BR Townhouse",
    slug: "lavington-greenery-3br-townhouse",
    subcategory: "houses",
    price: 160000,
    compare_price: 175000,
    short_description: "Spacious 3BR townhouse in a quiet gated court of only 6 units with private garden, detached DSQ, and solar water heating.",
    description: `Peaceful family living in prime Lavington near St. Austin's and Jaffery's Sports Club. Features a bright modern kitchen, separate dining room, family TV room upstairs, and a secure private garden.`,
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Pets allowed", "Private Compound", "Backup Generator"],
    is_featured: false,
    rating: 4.8,
    review_count: 22,
    rental_attributes: {
      listing_type: "house",
      property_type: "Townhouse",
      bedrooms: 3,
      bathrooms: 3,
      rent_period: "month",
      deposit_amount: 320000,
      area_sqm: 230,
      floor: "2 Storey",
      year_built: 2020,
      pets_allowed: true,
      parking_spaces: 2,
      furnished: false,
      amenities: ["Private Lawn", "Detached DSQ", "Solar Water Heating", "Borehole Water", "Quiet Court"],
      location_text: "James Gichuru Rd, Lavington, Nairobi",
      address: "Greenery Court, Villa 3",
      city: "Nairobi",
      neighborhood: "Lavington",
      coordinates: { lat: -1.2785, lng: 36.7692 },
      agent: {
        name: "Alaya Saunders",
        role: "Senior Leasing Partner",
        phone: "+254712345678",
        whatsapp: "+254712345678",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.9,
        reviews_count: 112,
        experience_years: 6,
        active_ads_count: 14,
      },
    },
  },
  {
    title: "South B Plainsview 1BR Apartment",
    slug: "south-b-plainsview-1br-apartment",
    subcategory: "apartments",
    price: 25000,
    compare_price: 27000,
    short_description: "Modern 1BR apartment just 10 mins from Nairobi CBD with excellent commuter access, secure parking, and clean finishes.",
    description: `Strategically located in South B near Mater Hospital and Mombasa Road. Offers easy transit access to the CBD, tiled floors, fitted kitchen cabinets, and dependable water storage.`,
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Near Transit", "Balcony", "Affordable"],
    is_featured: false,
    rating: 4.5,
    review_count: 18,
    rental_attributes: {
      listing_type: "apartment",
      property_type: "Apartment",
      bedrooms: 1,
      bathrooms: 1,
      rent_period: "month",
      deposit_amount: 25000,
      area_sqm: 55,
      floor: "2/5",
      year_built: 2021,
      pets_allowed: false,
      parking_spaces: 1,
      furnished: false,
      amenities: ["Close to CBD & Expressway", "Constant Water", "CCTV", "Perimeter Wall", "Balcony"],
      location_text: "Plainsview Rd, South B, Nairobi",
      address: "Plainsview Court Apt 2B",
      city: "Nairobi",
      neighborhood: "South B",
      coordinates: { lat: -1.3125, lng: 36.8375 },
      agent: {
        name: "David Kimani",
        role: "Leasing Specialist",
        phone: "+254722998877",
        whatsapp: "+254722998877",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.8,
        reviews_count: 54,
        experience_years: 4,
        active_ads_count: 8,
      },
    },
  },
  {
    title: "Parklands Diamond 2BR Furnished Haven",
    slug: "parklands-diamond-2br-furnished-haven",
    subcategory: "apartments",
    price: 75000,
    compare_price: 82000,
    short_description: "Tastefully furnished 2-bedroom apartment along 4th Parklands Ave with gym, solar heating, and 24hr armed security.",
    description: `Enjoy the convenience of Parklands living minutes away from Aga Khan University Hospital and City Park. Features contemporary furniture, high-speed WiFi, smart TV, and secure basement parking.`,
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Furnished", "Gym", "Modern Interior"],
    is_featured: false,
    rating: 4.8,
    review_count: 24,
    rental_attributes: {
      listing_type: "apartment",
      property_type: "Apartment",
      bedrooms: 2,
      bathrooms: 2,
      rent_period: "month",
      deposit_amount: 75000,
      area_sqm: 95,
      floor: "4/8",
      year_built: 2022,
      pets_allowed: false,
      parking_spaces: 1,
      furnished: true,
      amenities: ["Fully Furnished", "Gymnasium", "Backup Generator", "Borehole Water", "Card Access"],
      location_text: "4th Parklands Ave, Nairobi",
      address: "Diamond Suites Apt 4A",
      city: "Nairobi",
      neighborhood: "Parklands",
      coordinates: { lat: -1.2612, lng: 36.8224 },
      agent: {
        name: "Grace Mwangi",
        role: "Property Consultant",
        phone: "+254733445566",
        whatsapp: "+254733445566",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 5.0,
        reviews_count: 89,
        experience_years: 9,
        active_ads_count: 18,
      },
    },
  },
  {
    title: "Nyali Beachfront 3BR Ocean Breeze Villa",
    slug: "nyali-beachfront-3br-ocean-breeze-villa",
    subcategory: "beachfront",
    price: 130000,
    compare_price: 150000,
    short_description: "Stunning 3BR coastal villa in Nyali with direct private access to the white sandy beach, infinity pool, and coastal gardens.",
    description: `Coastal luxury at its finest. Wake up to panoramic Indian Ocean sunrises and refreshing ocean breezes. Includes large covered verandas, Swahili architectural accents, private swimming pool, and solar backup.`,
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    tags: ["Beachfront", "Verified", "Ocean View", "Swimming Pool", "Pets allowed"],
    is_featured: true,
    featured_rank: 4,
    rating: 5.0,
    review_count: 36,
    rental_attributes: {
      listing_type: "house",
      property_type: "Villa",
      bedrooms: 3,
      bathrooms: 3,
      rent_period: "month",
      deposit_amount: 260000,
      area_sqm: 280,
      floor: "2 Storey",
      year_built: 2021,
      pets_allowed: true,
      parking_spaces: 3,
      furnished: true,
      amenities: ["Direct Beach Access", "Private Infinity Pool", "Air Conditioned Bedrooms", "Solar Power System", "24/7 Guards"],
      location_text: "Links Rd, Nyali, Mombasa",
      address: "Nyali Beachfront Estate Villa 5",
      city: "Mombasa",
      neighborhood: "Nyali",
      coordinates: { lat: -4.0435, lng: 39.7025 },
      agent: {
        name: "Grace Mwangi",
        role: "Coastal Estates Director",
        phone: "+254733445566",
        whatsapp: "+254733445566",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 5.0,
        reviews_count: 89,
        experience_years: 9,
        active_ads_count: 18,
      },
    },
  },
  {
    title: "Kikuyu Mountainview Executive Bedsitter",
    slug: "kikuyu-mountainview-executive-bedsitter",
    subcategory: "rooms",
    price: 14000,
    compare_price: 16000,
    short_description: "Budget-friendly, ultra-clean executive bedsitter with reliable water, tiled floor, and quick access to the Southern Bypass.",
    description: `Great option for university students and young professionals. Features instant hot shower, fitted sink with marble counter, balcony for laundry, and 24hr caretaker on premises.`,
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1200&q=80",
    tags: ["Affordable", "Verified", "Water 24/7", "Bedsitter"],
    is_featured: false,
    rating: 4.7,
    review_count: 14,
    rental_attributes: {
      listing_type: "room",
      property_type: "Bedsitter / Studio",
      bedrooms: 0,
      bathrooms: 1,
      rent_period: "month",
      deposit_amount: 14000,
      area_sqm: 35,
      floor: "1/4",
      year_built: 2022,
      pets_allowed: false,
      parking_spaces: 1,
      furnished: false,
      amenities: ["Borehole Water On-site", "Instant Shower", "CCTV Security", "Near Southern Bypass"],
      location_text: "Ondiri Rd, Kikuyu, Kiambu",
      address: "Mountainview Apartments Rm 104",
      city: "Nairobi",
      neighborhood: "Kikuyu",
      coordinates: { lat: -1.2465, lng: 36.6625 },
      agent: {
        name: "David Kimani",
        role: "Leasing Specialist",
        phone: "+254722998877",
        whatsapp: "+254722998877",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.8,
        reviews_count: 54,
        experience_years: 4,
        active_ads_count: 8,
      },
    },
  },
  {
    title: "Kilimani Silver Oak 1BR Furnished Suite",
    slug: "kilimani-silver-oak-1br-furnished-suite",
    subcategory: "apartments",
    price: 60000,
    compare_price: 68000,
    short_description: "Modern serviced 1-bedroom suite in Kilimani near Yaya Centre with swimming pool, gym, high-speed WiFi, and housekeeping.",
    description: `Designed for comfortable mid-to-long term rentals. Complete with comfy queen bed, smart TV with Netflix, washing machine, open-concept kitchen, and access to the heated rooftop pool.`,
    images: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80",
    tags: ["Verified", "Furnished", "Swimming Pool", "Fibre WiFi"],
    is_featured: false,
    rating: 4.9,
    review_count: 34,
    rental_attributes: {
      listing_type: "apartment",
      property_type: "Apartment",
      bedrooms: 1,
      bathrooms: 1,
      rent_period: "month",
      deposit_amount: 60000,
      area_sqm: 65,
      floor: "6/10",
      year_built: 2023,
      pets_allowed: false,
      parking_spaces: 1,
      furnished: true,
      amenities: ["Swimming Pool", "Fully Equipped Gym", "High-speed WiFi", "Full Backup Generator", "Housekeeping Included"],
      location_text: "Chania Ave, Kilimani, Nairobi",
      address: "Silver Oak Residence Suite 602",
      city: "Nairobi",
      neighborhood: "Kilimani",
      coordinates: { lat: -1.2915, lng: 36.7935 },
      agent: {
        name: "Alaya Saunders",
        role: "Senior Leasing Partner",
        phone: "+254712345678",
        whatsapp: "+254712345678",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.9,
        reviews_count: 112,
        experience_years: 6,
        active_ads_count: 14,
      },
    },
  },
  {
    title: "Riverside Parkview 4BR Duplex Penthouse",
    slug: "riverside-parkview-4br-duplex-penthouse",
    subcategory: "houses",
    price: 280000,
    compare_price: 310000,
    short_description: "Spectacular 4BR duplex penthouse spanning 380 sqm with private rooftop plunge pool, servant quarters, and panoramic forest views.",
    description: `A masterwork of architecture along Riverside Drive. Spread over two expansive levels with private elevator access, double-height ceilings, Italian designer kitchen, family lounge, and private rooftop plunge pool.`,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    tags: ["Exclusive", "Verified", "Panoramic View", "Private Lift", "Gym & Pool"],
    is_featured: true,
    featured_rank: 5,
    rating: 5.0,
    review_count: 27,
    rental_attributes: {
      listing_type: "house",
      property_type: "Penthouse",
      bedrooms: 4,
      bathrooms: 4,
      rent_period: "month",
      deposit_amount: 560000,
      area_sqm: 380,
      floor: "11/11",
      year_built: 2023,
      pets_allowed: true,
      parking_spaces: 3,
      furnished: true,
      amenities: ["Private Rooftop Plunge Pool", "Private Keycard Elevator", "DSQ for 2", "Heated Pool & Spa", "Full Backup Generator"],
      location_text: "Riverside Drive, Nairobi",
      address: "Parkview Tower Duplex 1101",
      city: "Nairobi",
      neighborhood: "Riverside",
      coordinates: { lat: -1.2715, lng: 36.7975 },
      agent: {
        name: "Grace Mwangi",
        role: "Luxury Estates Director",
        phone: "+254733445566",
        whatsapp: "+254733445566",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 5.0,
        reviews_count: 89,
        experience_years: 9,
        active_ads_count: 18,
      },
    },
  },
  {
    title: "Ngong Road Co-working & Private Office Hub",
    slug: "ngong-road-coworking-private-office-hub",
    subcategory: "commercial",
    price: 55000,
    compare_price: 65000,
    short_description: "Ready-to-move-in private commercial office suite for up to 8 people with boardroom credits, reception, and high-speed fiber.",
    description: `Ideal for tech startups, creative agencies, and growing consultancy teams. Includes ergonomic desks, high speed mesh Wi-Fi, shared boardroom access, kitchen with espresso machine, and 24/7 biometric security.`,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    tags: ["Commercial", "Fibre High-speed", "Boardroom Access", "Verified"],
    is_featured: false,
    rating: 4.8,
    review_count: 19,
    rental_attributes: {
      listing_type: "commercial",
      property_type: "Commercial Office",
      bedrooms: 0,
      bathrooms: 2,
      rent_period: "month",
      deposit_amount: 55000,
      area_sqm: 85,
      floor: "3/5",
      year_built: 2021,
      pets_allowed: false,
      parking_spaces: 2,
      furnished: true,
      amenities: ["High-speed 100Mbps Fibre", "Boardroom Access", "Reception Services", "Espresso Bar", "Full Backup Generator"],
      location_text: "Ngong Rd near Junction Mall, Nairobi",
      address: "The Hub Arcade Suite 304",
      city: "Nairobi",
      neighborhood: "Ngong Road",
      coordinates: { lat: -1.3025, lng: 36.7725 },
      agent: {
        name: "David Kimani",
        role: "Commercial Specialist",
        phone: "+254722998877",
        whatsapp: "+254722998877",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
        verified: true,
        rating: 4.8,
        reviews_count: 54,
        experience_years: 4,
        active_ads_count: 8,
      },
    },
  },
];
