/**
 * Default Seed Dataset: 28 Realistic Retail Products & 6 Verified Kenyan Stores
 * Styled for high-fidelity retail e-commerce experiences matching modern shop UI.
 */

export const DEFAULT_RETAIL_STORES = [
  {
    name: "Tech Haven Electronics",
    slug: "tech-haven-electronics",
    tagline: "Your Premier Hub for Modern Gadgets & Computing",
    description: "Official distributor of certified personal computing, high-fidelity audio, smart displays, and visual equipment across East Africa.",
    location: "Sarit Centre, Westlands, Nairobi",
    rating: 4.9,
    review_count: 1135,
    badges: ["Verified Store", "Best Seller", "Daily Deals"],
    banner: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1200&q=80",
    avatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80",
    category: "Electronics & Computing",
  },
  {
    name: "Harmony Haven",
    slug: "harmony-haven",
    tagline: "Contemporary Living, Home Aesthetics & Appliances",
    description: "Curated kitchen appliances, ergonomic furnishings, and modern home essentials designed for elevated living.",
    location: "Two Rivers Mall, Limuru Rd, Nairobi",
    rating: 4.8,
    review_count: 840,
    badges: ["Verified Store", "Best Seller"],
    banner: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    avatar: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=300&q=80",
    category: "Appliances & Home",
  },
  {
    name: "Simtech Computers",
    slug: "simtech-computers",
    tagline: "Shop Smart, Live Stylish",
    description: "High performance laptops, gaming rigs, professional eye-care monitors, and certified business desktop workstations.",
    location: "Biashara Street, Nairobi CBD",
    rating: 4.9,
    review_count: 920,
    badges: ["Verified Store", "Fast Shipping"],
    banner: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    avatar: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=300&q=80",
    category: "Computers & Gaming",
  },
  {
    name: "UrbanCart Lifestyle",
    slug: "urbancart-lifestyle",
    tagline: "Discover Deals, Redefine Shopping",
    description: "Modern fashion apparel, handcrafted genuine leather footwear, designer bags, and premium cosmetics & skincare.",
    location: "Yaya Centre, Kilimani, Nairobi",
    rating: 4.8,
    review_count: 675,
    badges: ["Verified Store", "Mega Discounts"],
    banner: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80",
    avatar: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=300&q=80",
    category: "Fashion & Beauty",
  },
  {
    name: "SwiftBazaar Supermarket",
    slug: "swiftbazaar-supermarket",
    tagline: "Fast Finds, Easy Buys & Everyday Freshness",
    description: "Fresh groceries, baby care essentials, pantry staples, and household cleaning supplies delivered straight to your door.",
    location: "Kilimani Business Plaza, Nairobi",
    rating: 4.8,
    review_count: 1420,
    badges: ["Verified Store", "Daily Deals", "Same-Day Delivery"],
    banner: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=80",
    avatar: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=300&q=80",
    category: "Groceries & Supermarket",
  },
  {
    name: "Opulence Outlet",
    slug: "opulence-outlet",
    tagline: "Luxury Watches, Smart Wearables & Premium Audio",
    description: "Direct importer of next-gen smartwatches, active noise cancellation acoustics, and luxury personal accessories.",
    location: "The Hub Karen, Dagoretti Rd, Nairobi",
    rating: 4.8,
    review_count: 780,
    badges: ["Verified Store", "Best Seller"],
    banner: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=1200&q=80",
    avatar: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=300&q=80",
    category: "Watches & Wearables",
  },
];

export const DEFAULT_RETAIL_PRODUCTS = [
  // 1. HP Victus Ryzen 5 (Image 1)
  {
    title: "HP (Smart Choice) Victus Gaming Laptop AMD Ryzen 5 5600H 15.6\" FHD IPS",
    slug: "hp-victus-gaming-laptop-ryzen-5",
    brand: "HP",
    subcategory: "electronics",
    storeSlug: "simtech-computers",
    price: 84921,
    compare_price: 107500,
    discount_pct: 21,
    short_description: "HP Victus 15.6\" 144Hz FHD Gaming Laptop featuring AMD Ryzen 5 5600H, 16GB DDR4, 512GB NVMe SSD, and GeForce RTX 3050 graphics.",
    description: `Engineered for peak performance gaming and demanding creative workloads. Powered by the high-speed AMD Ryzen 5 5600H hexa-core processor and NVIDIA GeForce RTX 3050 dedicated graphics.
Features a crisp 15.6-inch 144Hz micro-edge anti-glare FHD IPS display, dual-fan thermal cooling system, Bang & Olufsen audio tuning, and backlit numeric keyboard. Pre-installed with Windows 11 Home.`,
    thumbnail: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "HP", "Gaming", "Laptops", "Ryzen 5", "RTX"],
    stock: 12,
    rating: 4.8,
    review_count: 14,
    is_featured: true,
    featured_rank: 1,
  },
  // 2. HP Victus Ryzen 7 (Image 1)
  {
    title: "HP Victus Gaming Laptop AMD Ryzen 7 5800H 15.6\" (39.6 cm) FHD IPS",
    slug: "hp-victus-gaming-laptop-ryzen-7",
    brand: "HP",
    subcategory: "electronics",
    storeSlug: "simtech-computers",
    price: 94960,
    compare_price: 118700,
    discount_pct: 20,
    short_description: "Pro-tier gaming beast with AMD Ryzen 7 5800H 8-core CPU, 16GB high-speed RAM, RTX 3060 6GB GDDR6, and 1TB SSD.",
    description: `Step up your gaming and rendering capabilities with the Ryzen 7 5800H powerhouse. Designed with upgraded heat-pipe architecture, 100% sRGB color-accurate display, Wi-Fi 6 connectivity, and customizable performance modes via OMEN Gaming Hub.`,
    thumbnail: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "HP", "Laptops", "Ryzen 7", "Gaming", "High-Performance"],
    stock: 8,
    rating: 4.9,
    review_count: 9,
    is_featured: true,
    featured_rank: 2,
  },
  // 3. Samsung 43" 4K Smart TV (Image 1)
  {
    title: "Samsung 108 cm (43 inches) Crystal iSmart 4K Ultra HD Smart LED TV",
    slug: "samsung-43-crystal-ismart-4k-uhd-tv",
    brand: "Samsung",
    subcategory: "electronics",
    storeSlug: "tech-haven-electronics",
    price: 48211,
    compare_price: 81700,
    discount_pct: 41,
    short_description: "Samsung 43-inch Crystal 4K UHD processor, HDR10+, OTS Lite sound, and smart Tizen OS with AirPlay & voice control.",
    description: `Billion True Colors come to life with the Crystal Processor 4K. Features dynamic crystal color technology, Motion Xcelerator for fluid gaming and sports action, Q-Symphony sound sync with Samsung soundbars, and sleek 3-side bezel-less design.`,
    thumbnail: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1461151304267-38535e780c79?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "Samsung", "TV", "4K", "Smart TV", "Crystal UHD"],
    stock: 15,
    rating: 4.9,
    review_count: 32,
    is_featured: true,
    featured_rank: 3,
  },
  // 4. realme 43" Full HD LED Smart Android TV (Image 1)
  {
    title: "realme 108 cm (43 inch) Full HD LED Smart Android TV (TV 43)",
    slug: "realme-43-inch-fhd-smart-android-tv",
    brand: "realme",
    subcategory: "electronics",
    storeSlug: "tech-haven-electronics",
    price: 29000,
    compare_price: 31200,
    discount_pct: 7,
    short_description: "Chroma Boost Picture Engine, 24W Quad Stereo Speakers with Dolby Audio, and official Android TV Google Play ecosystem.",
    description: `Delivers cinematic contrast with the proprietary Chroma Boost picture engine. Comes with built-in Chromecast, Google Assistant remote with voice search, and seamless Bluetooth 5.0 streaming.`,
    thumbnail: "https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "realme", "TV", "Android TV", "Smart TV"],
    stock: 19,
    rating: 4.6,
    review_count: 21,
    is_featured: false,
  },
  // 5. Sony HT-S20R Soundbar 5.1ch (Image 1)
  {
    title: "Sony HT-S20R Real 5.1ch Dolby Digital Soundbar with Subwoofer & Rear Speakers",
    slug: "sony-ht-s20r-5-1ch-soundbar-subwoofer",
    brand: "Sony",
    subcategory: "electronics",
    storeSlug: "tech-haven-electronics",
    price: 27993,
    compare_price: 37300,
    discount_pct: 25,
    short_description: "400W total power output, true 5.1 channel surround sound with wired rear speakers, external subwoofer, and HDMI ARC.",
    description: `Immerse yourself in authentic movie theatre sound right in your living room. The 5.1ch sound setup includes a discrete 3ch soundbar, rear satellite speakers, and deep punchy subwoofer, all driven by Dolby Digital cinema audio processing.`,
    thumbnail: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "Sony", "Soundbar", "Audio", "Home Theatre", "Dolby"],
    stock: 14,
    rating: 4.9,
    review_count: 18,
    is_featured: true,
    featured_rank: 4,
  },
  // 6. HP Chromebox Mini PC (Image 1)
  {
    title: "HP Chromebox High Performance Desktop Mini PC (Intel Core i7 8th Gen, 16GB RAM)",
    slug: "hp-chromebox-desktop-mini-pc-i7",
    brand: "HP",
    subcategory: "electronics",
    storeSlug: "simtech-computers",
    price: 37100,
    compare_price: 46400,
    discount_pct: 20,
    short_description: "Ultra-compact form factor desktop PC powered by Intel Core i7, 16GB RAM, dual 4K monitor support, and silent cooling.",
    description: `Compact footprint meets enterprise power. Excellent for business workstations, POS terminals, digital signage, and home office productivity with instant boot, automatic cloud backup, and versatile I/O ports including USB-C and HDMI.`,
    thumbnail: "https://images.unsplash.com/photo-1587831990711-23ca6441447b?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1587831990711-23ca6441447b?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "HP", "Mini PC", "Desktop", "Computers", "Business"],
    stock: 9,
    rating: 4.6,
    review_count: 11,
    is_featured: false,
  },
  // 7. BenQ GW2790 27" Eye-Care Monitor (Image 1)
  {
    title: "BenQ GW2790 27\" 1080p FHD 100Hz Eye-Care IPS Monitor with Built-in Speakers",
    slug: "benq-gw2790-27-fhd-100hz-eye-care-monitor",
    brand: "BenQ",
    subcategory: "electronics",
    storeSlug: "simtech-computers",
    price: 22490,
    compare_price: 28100,
    discount_pct: 20,
    short_description: "27-inch 100Hz refresh rate IPS display with Brightness Intelligence Gen2, Low Blue Light Plus, and dual HDMI.",
    description: `Work comfortably for hours without eye strain. BenQ's exclusive Brightness Intelligence sensor actively detects ambient lighting and automatically adjusts screen brightness and color temperature for supreme eye comfort.`,
    thumbnail: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "BenQ", "Monitors", "Eye-Care", "Displays", "FHD"],
    stock: 16,
    rating: 4.8,
    review_count: 24,
    is_featured: false,
  },
  // 8. BenQ GW2490 23.8" Monitor (Image 1)
  {
    title: "BenQ GW2490 23.8\" 1080p FHD 100Hz Eye-Care IPS Desktop Monitor",
    slug: "benq-gw2490-24-fhd-100hz-monitor",
    brand: "BenQ",
    subcategory: "electronics",
    storeSlug: "simtech-computers",
    price: 13690,
    compare_price: 19000,
    discount_pct: 28,
    short_description: "Crisp 23.8\" frameless design, 100Hz smooth motion, e-Paper mode, Coding mode, and integrated audio speakers.",
    description: `The benchmark compact office and coding monitor. With specialized color modes designed for programmers and readers, high color accuracy, and TÜV Rheinland certified flicker-free backlighting.`,
    thumbnail: "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "BenQ", "Monitors", "Office", "Displays"],
    stock: 22,
    rating: 4.7,
    review_count: 19,
    is_featured: false,
  },
  // 9. Sony WH-CH720N Noise Canceling Headphones (Image 1)
  {
    title: "Sony WH-CH720N Wireless Over-Ear Active Noise Cancellation Headphones",
    slug: "sony-wh-ch720n-anc-wireless-headphones",
    brand: "Sony",
    subcategory: "electronics",
    storeSlug: "opulence-outlet",
    price: 11945,
    compare_price: 17100,
    discount_pct: 30,
    short_description: "Dual Noise Sensor technology, Integrated Processor V1, up to 35 hours battery life, and lightweight ergonomic fit.",
    description: `Block out background office noise or travel commotion. Equipped with Sony's V1 processor for distortion-free crystal audio, multipoint connection to switch between laptop and phone, and ultra-clear hands-free microphone calls.`,
    thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "Sony", "Audio", "Headphones", "Noise Cancellation", "Wireless"],
    stock: 18,
    rating: 4.9,
    review_count: 45,
    is_featured: true,
    featured_rank: 5,
  },
  // 10. Philips Mixer Grinder 750W (Image 1)
  {
    title: "Philips HL7756 Mixer Grinder 750 Watt with 3 Stainless Steel Multipurpose Jars",
    slug: "philips-hl7756-mixer-grinder-750w",
    brand: "Philips",
    subcategory: "appliances",
    storeSlug: "harmony-haven",
    price: 6024,
    compare_price: 8250,
    discount_pct: 27,
    short_description: "Heavy-duty 750W Turbo motor, advanced air ventilation, specialized blades for tough Kenyan spices and grains.",
    description: `Engineered for effortless dry grinding, wet blending, and chutney preparation. Built with heavy gauge 304 food-grade stainless steel jars with leak-proof rubber gaskets, ergonomic grip handles, and overload safety cut-off protection.`,
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Appliances", "Philips", "Kitchen", "Mixer", "Grinder", "Cooking"],
    stock: 25,
    rating: 4.8,
    review_count: 38,
    is_featured: false,
  },
  // 11. Men's Tan Formal Moccasin (Image 1)
  {
    title: "Men's Tan Formal Moccasin Genuine Leather Italian Loafers",
    slug: "mens-tan-formal-moccasin-leather-loafers",
    brand: "Napa Leather",
    subcategory: "footwear",
    storeSlug: "urbancart-lifestyle",
    price: 5500,
    compare_price: 7500,
    discount_pct: 27,
    short_description: "Handcrafted calfskin leather loafers with cushioned insole, breathable inner lining, and non-slip rubber outsoles.",
    description: `Classic elegance tailored for boardroom meetings and formal evening ceremonies. Meticulously finished with hand-stitched detailing, arch-supporting memory foam footbeds, and premium burnished tan polish.`,
    thumbnail: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Footwear", "Fashion", "Men's Shoes", "Leather", "Formal", "Loafers"],
    stock: 14,
    rating: 4.7,
    review_count: 15,
    is_featured: false,
  },
  // 12. The Ultimate Makeup Kit (Image 1)
  {
    title: "The Ultimate Makeup Kit & Professional 48-Shade Beauty Palette",
    slug: "the-ultimate-makeup-kit-beauty-palette",
    brand: "Urban Beauty",
    subcategory: "beauty",
    storeSlug: "urbancart-lifestyle",
    price: 4500,
    compare_price: 6000,
    discount_pct: 25,
    short_description: "All-in-one beauty trunk with matte and shimmer eyeshadows, waterproof lipsticks, blushers, and contour brushes.",
    description: `Everything you need to create runway-ready glam or effortless everyday natural looks. Hypoallergenic, dermatologist-tested formulas with all-day crease-free stay and rich color payoff for all African skin tones.`,
    thumbnail: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Beauty", "Cosmetics", "Makeup", "Skincare", "Palettes", "Lipstick"],
    stock: 30,
    rating: 4.8,
    review_count: 29,
    is_featured: false,
  },
  // 13. Philips Viva Induction Cooktop (Image 1)
  {
    title: "Philips Viva Collection HD4928/01 2100-Watt Electromagnetic Induction Cooktop",
    slug: "philips-viva-2100w-induction-cooktop",
    brand: "Philips",
    subcategory: "appliances",
    storeSlug: "harmony-haven",
    price: 5477,
    compare_price: 7500,
    discount_pct: 27,
    short_description: "Programmed for efficient Kenyan cooking, electromagnetic crystal glass surface, auto-off timer, and rapid heating.",
    description: `Cut cooking time and energy costs in half. Features customized temperature controls for boiling milk, preparing tea, deep frying, and simmer modes, plus cool-to-touch ceramic crystal glass for easy wipe-down cleaning.`,
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Appliances", "Philips", "Kitchen", "Cooktop", "Energy-Saving", "Home"],
    stock: 20,
    rating: 4.8,
    review_count: 33,
    is_featured: false,
  },
  // 14. Napa Hide Leather Bag (Image 1)
  {
    title: "Napa Hide Handcrafted Full-Grain Leather Travel Duffel & Organizer Bag",
    slug: "napa-hide-leather-travel-bag",
    brand: "Napa Hide",
    subcategory: "fashion",
    storeSlug: "urbancart-lifestyle",
    price: 3545,
    compare_price: 4990,
    discount_pct: 29,
    short_description: "Vintage brown genuine leather weekend bag with reinforced antique brass hardware and padded laptop sleeve.",
    description: `Constructed from sustainably tanned top-grain leather that ages with a rich natural patina. Includes dedicated shoe compartment, weather-resistant inner lining, and detachable adjustable shoulder strap.`,
    thumbnail: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Fashion", "Leather", "Bags", "Travel", "Accessories", "Luggage"],
    stock: 17,
    rating: 4.9,
    review_count: 12,
    is_featured: false,
  },
  // 15. BeatXP Smart Watch 32 (Image 1)
  {
    title: "BeatXP Marv Raze 1.96\" Ultra HD Display Smartwatch with Bluetooth Calling",
    slug: "beatxp-marv-raze-smartwatch",
    brand: "BeatXP",
    subcategory: "mobiles",
    storeSlug: "opulence-outlet",
    price: 2999,
    compare_price: 4999,
    discount_pct: 40,
    short_description: "1.96\" curved glass display, clear AI Bluetooth calling, 24/7 heart rate & SpO2 biometric tracking, IP68 water resistant.",
    description: `Stay connected on the move without pulling your smartphone out. With crystal-clear speaker and microphone for phone calls, 100+ fitness and sports modes, sleep tracking, and up to 7 days standby battery life.`,
    thumbnail: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Mobiles", "BeatXP", "Smartwatch", "Wearables", "Fitness", "Gadgets"],
    stock: 35,
    rating: 4.6,
    review_count: 52,
    is_featured: false,
  },
  // 16. BeatXP Smart Watch 33 (Image 1)
  {
    title: "BeatXP Flare Pro 1.39\" Round Dial Bluetooth Calling Metallic Smartwatch",
    slug: "beatxp-flare-pro-round-smartwatch",
    brand: "BeatXP",
    subcategory: "mobiles",
    storeSlug: "opulence-outlet",
    price: 2499,
    compare_price: 3999,
    discount_pct: 38,
    short_description: "Premium metallic bezel round dial, 500 nits high brightness display, AI voice assistant, and multi-sport tracker.",
    description: `Combines classic timepiece aesthetics with next-gen smart notifications. Receive WhatsApp and SMS previews, control smartphone music, track daily calories and steps, and recharge rapidly via magnetic charger.`,
    thumbnail: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Mobiles", "BeatXP", "Smartwatch", "Wearables", "Watches"],
    stock: 28,
    rating: 4.5,
    review_count: 41,
    is_featured: false,
  },
  // 17. BeatXP Smart Watch 34 (Image 1)
  {
    title: "BeatXP Vega 1.43\" AMOLED Display Smartwatch with Always-On Screen",
    slug: "beatxp-vega-amoled-smartwatch",
    brand: "BeatXP",
    subcategory: "mobiles",
    storeSlug: "opulence-outlet",
    price: 3499,
    compare_price: 5499,
    discount_pct: 36,
    short_description: "1000 nits Super AMOLED display, 60Hz smooth refresh rate, rotating crown navigation, and continuous vital monitoring.",
    description: `Stunning vivid blacks and brilliant contrast in direct sunlight. Includes fast wireless charging, customized watch faces, menstrual cycle reminder, stress monitoring, and durable zinc alloy chassis.`,
    thumbnail: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Mobiles", "BeatXP", "Smartwatch", "AMOLED", "Wearables"],
    stock: 21,
    rating: 4.7,
    review_count: 28,
    is_featured: false,
  },
  // 18. Levi's Women's Sweater (Image 1)
  {
    title: "Levi's Women's Brand Logo Printed 100% Cotton Crew Neck Sweater",
    slug: "levis-womens-crewneck-logo-sweater",
    brand: "Levi's",
    subcategory: "clothing",
    storeSlug: "urbancart-lifestyle",
    price: 2240,
    compare_price: 3599,
    discount_pct: 38,
    short_description: "Cozy relaxed-fit French terry cotton pullover featuring iconic Levi's red batwing logo print.",
    description: `Everyday casual style with unmatched comfort. Crafted from soft, breathable pure ring-spun cotton with ribbed cuffs and hem, designed to keep its vibrant color and shape through repeated washes.`,
    thumbnail: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Clothing", "Levi's", "Women's Fashion", "Sweater", "Cotton", "Apparel"],
    stock: 24,
    rating: 4.8,
    review_count: 16,
    is_featured: false,
  },
  // 19. Levi's Men's Sweatshirt (Image 1)
  {
    title: "Levi's Men's Graphic Heavyweight Fleece Hooded Sweatshirt - Deep Red",
    slug: "levis-mens-heavyweight-fleece-hoodie",
    brand: "Levi's",
    subcategory: "clothing",
    storeSlug: "urbancart-lifestyle",
    price: 2920,
    compare_price: 4200,
    discount_pct: 30,
    short_description: "Classic kangaroo pocket fleece hoodie with double-layer hood, drawstrings, and heritage embroidery.",
    description: `The essential winter warmer. Made with heavy-duty brushed fleece fabric on the interior for maximum thermal retention during chilly Nairobi mornings, paired with stylish ribbed athletic trim.`,
    thumbnail: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Clothing", "Levi's", "Men's Fashion", "Hoodie", "Sweatshirt", "Winter"],
    stock: 19,
    rating: 4.7,
    review_count: 22,
    is_featured: false,
  },
  // 20. Puma Women's Slides (Image 1)
  {
    title: "Puma Women's Popcat 20 Floral Comfort Lightweight Slides",
    slug: "puma-womens-popcat-floral-slides",
    brand: "Puma",
    subcategory: "footwear",
    storeSlug: "urbancart-lifestyle",
    price: 1875,
    compare_price: 2499,
    discount_pct: 25,
    short_description: "Ultra-cushioned molded EVA footbed with padded floral strap, quick-dry technology, and textured grip outsole.",
    description: `Step into pure cloud-like comfort after a workout, at the pool, or for relaxed lounge days at home. Features an anatomical contoured footbed for all-day arch support and durable waterproof construction.`,
    thumbnail: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Footwear", "Puma", "Slides", "Women's Footwear", "Comfort", "Sandals"],
    stock: 32,
    rating: 4.6,
    review_count: 31,
    is_featured: false,
  },
  // 21. Office Chair & Metal Work Table (Image 2)
  {
    title: "Ergonomic Office Executive Chair with Metal Work Table & Visitor's Chairs Set",
    slug: "ergonomic-office-executive-chair-table-set",
    brand: "ACME Corp",
    subcategory: "furniture",
    storeSlug: "harmony-haven",
    price: 38500,
    compare_price: 49000,
    discount_pct: 21,
    short_description: "Complete modern workstation bundle with breathable mesh ergonomic swivel chair, steel frame desk, and 2 visitor chairs.",
    description: `Transform your workspace into a modern executive hub. Heavy-duty powder-coated steel frame desk with cable management grommets, lumbar-supporting pneumatic lift task chair, and matched cantilever visitor seating.`,
    thumbnail: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Furniture", "Office", "Chairs", "Desk", "Workstation", "Executive"],
    stock: 7,
    rating: 4.9,
    review_count: 17,
    is_featured: true,
    featured_rank: 6,
  },
  // 22. Master Chef Cookware Pots 4 Pieces (Image 2)
  {
    title: "Master Chef Nonstick Pots & Pans Induction Cookware Set - 4 Pieces with Glass Lids",
    slug: "master-chef-nonstick-pots-4-pieces",
    brand: "Master Chef",
    subcategory: "appliances",
    storeSlug: "harmony-haven",
    price: 9200,
    compare_price: 12500,
    discount_pct: 26,
    short_description: "Granite stone nonstick coating, induction compatible aluminum core, stay-cool bakelite handles, and tempered vents.",
    description: `Cook healthy, oil-free meals with zero food sticking. Includes 24cm Dutch oven casserole, 20cm sauce pot, 24cm deep sauté skillet, and 16cm milk saucepan, all completely free of PFOA, lead, and cadmium.`,
    thumbnail: "https://images.unsplash.com/photo-1584990347449-397a61d15582?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1584990347449-397a61d15582?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Appliances", "Kitchen", "Cookware", "Pots", "Master Chef", "Nonstick"],
    stock: 15,
    rating: 4.8,
    review_count: 39,
    is_featured: false,
  },
  // 23. Girls' Pretty Dress - Red (Image 2)
  {
    title: "Girls' Pretty Floral Evening Maxi Dress - Scarlet Red with Belt Tie",
    slug: "girls-pretty-floral-maxi-dress-red",
    brand: "TrendHive",
    subcategory: "clothing",
    storeSlug: "urbancart-lifestyle",
    price: 3890,
    compare_price: 5200,
    discount_pct: 25,
    short_description: "Flowing chiffon A-line silhouette with pleated balloon sleeves, tier ruffles, and adjustable waist ribbon.",
    description: `A show-stopping red statement dress perfect for family gatherings, weddings, and celebration parties. Breathable inner lining ensures all-day comfort without transparency, while the flowing hem adds graceful motion.`,
    thumbnail: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Clothing", "Women's Fashion", "Dress", "Evening", "Floral", "Red"],
    stock: 18,
    rating: 4.7,
    review_count: 14,
    is_featured: false,
  },
  // 24. Babyganics Liquid Soap (Image 2)
  {
    title: "Babyganics Baby Bottle Liquid Soap & Dish Cleanser (Fragrance Free, 473ml)",
    slug: "babyganics-baby-bottle-liquid-soap-473ml",
    brand: "Babyganics",
    subcategory: "groceries",
    storeSlug: "swiftbazaar-supermarket",
    price: 1650,
    compare_price: 2100,
    discount_pct: 21,
    short_description: "Plant-derived dish cleanser formulated to target milk film and breastmilk residue without harsh toxins.",
    description: `Gentle for baby essentials, uncompromising against grime. Hypoallergenic, pediatrician and dermatologist tested, formulated with no phosphates, phthalates, synthetic fragrances, or dyes.`,
    thumbnail: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Groceries", "Baby Care", "Soap", "Organic", "Cleanser", "Household"],
    stock: 45,
    rating: 4.9,
    review_count: 58,
    is_featured: false,
  },
  // 25. Samsung Galaxy Tab A (Image 2)
  {
    title: "Samsung Galaxy Tab A 8.0\" (32GB ROM, 4GB RAM 4G LTE Tablet with S-Pen)",
    slug: "samsung-galaxy-tab-a-8-inch-lte",
    brand: "Samsung",
    subcategory: "mobiles",
    storeSlug: "tech-haven-electronics",
    price: 18500,
    compare_price: 24000,
    discount_pct: 23,
    short_description: "Slim metal unibody, long-lasting 5100mAh battery, dual speakers, and vibrant 8.0\" HD WXGA display.",
    description: `Lightweight tablet built for study, reading, video calls, and field work. Easily slides into one hand or a small purse. Includes Samsung Kids mode, expandable storage up to 512GB via microSD, and crisp rear/front cameras.`,
    thumbnail: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Mobiles", "Samsung", "Tablet", "Android", "4G LTE", "Gadgets"],
    stock: 16,
    rating: 4.6,
    review_count: 26,
    is_featured: false,
  },
  // 26. Apple iPad Pro 12.9" (Image 2)
  {
    title: "Apple iPad Pro 12.9\" M2 Chip (512GB WiFi + Cellular, Space Grey with Liquid Retina XDR)",
    slug: "apple-ipad-pro-12-9-m2-512gb",
    brand: "Apple",
    subcategory: "mobiles",
    storeSlug: "tech-haven-electronics",
    price: 145000,
    compare_price: 169000,
    discount_pct: 14,
    short_description: "Supercharged by the M2 chip, 12.9\" Liquid Retina XDR display with ProMotion 120Hz, Thunderbolt 4, and 5G.",
    description: `The ultimate iPad experience. Features breathtaking 1,600 nits peak brightness, 12MP Wide and 10MP Ultra Wide back cameras with LiDAR scanner, Center Stage front camera, and Apple Pencil hover technology.`,
    thumbnail: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Mobiles", "Apple", "iPad Pro", "Tablets", "M2", "Pro"],
    stock: 5,
    rating: 5.0,
    review_count: 48,
    is_featured: true,
    featured_rank: 7,
  },
  // 27. Nikon D5500 DSLR Camera (Image 2)
  {
    title: "Nikon D5500 DSLR Camera with AF-P 18-55mm VR Lens Kit & 24.2MP Sensor",
    slug: "nikon-d5500-dslr-camera-lens-kit",
    brand: "Nikon",
    subcategory: "electronics",
    storeSlug: "tech-haven-electronics",
    price: 52000,
    compare_price: 65000,
    discount_pct: 20,
    short_description: "24.2 MP DX-format CMOS sensor, EXPEED 4 processor, 3.2\" vari-angle touchscreen, Full HD 1080/60p video.",
    description: `Capture sharp, richly colored stills and cinematic videos. Equipped with a versatile vari-angle flip touchscreen for high- and low-angle shots, built-in Wi-Fi for instant photo sharing, and 39-point autofocus system.`,
    thumbnail: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "Nikon", "Camera", "DSLR", "Photography", "Video"],
    stock: 8,
    rating: 4.9,
    review_count: 36,
    is_featured: false,
  },
  // 28. Acer 28" 4K Monitor (Image 2)
  {
    title: "Acer KG281K 28-inch Ultra HD 4K Gaming Monitor with AMD FreeSync & 1ms Response",
    slug: "acer-kg281k-28-inch-4k-gaming-monitor",
    brand: "Acer",
    subcategory: "electronics",
    storeSlug: "simtech-computers",
    price: 36500,
    compare_price: 45000,
    discount_pct: 19,
    short_description: "3840 x 2160 4K UHD resolution, 1ms lightning response time, AMD FreeSync tear-free gaming, and dual HDMI 2.0.",
    description: `Spectacular 4K pixel density for razor-sharp gaming and spreadsheet mastery. Includes Acer VisionCare technology with BlueLightShield and ComfyView glare reduction to reduce fatigue during extended work marathons.`,
    thumbnail: "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Electronics", "Acer", "Monitors", "4K", "Gaming", "Displays"],
    stock: 11,
    rating: 4.8,
    review_count: 23,
    is_featured: false,
  },
];
